Select * from Users
Select * from Portfolios
Select * from Transactions
Select * from Alerts
Select * from Dividends 
Select * from Watchlist
Select * from MarketIndices
Select * from IndexComponents 
Select * from Stocks
Select * from HistoricalPrices
Select * from RealTimePrices